# Operasi Matematika & Numpy

In [2]:
import numpy as np

### Latihan-2 (2D array)

In [37]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
#Lengkapi kodingan berikut
print('banyaknya entry = ', A.size)
print('dimensi array = ', A.ndim )
print('ukuran array = ', A.shape )

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


### Latihan-3 (Slicing)

In [50]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
#Lengkapi kodingan berikut
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,:2]  )
print('entry ke-2 & 3 kolom ke-3 = ',A[1:,2] )

baris ke-3 =  [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 =  [6 9]


output jawaban:
baris ke-3 =  [7 8 9]

entry ke-1 & 2 baris ke-3 =  [7 8]

entry ke-2 & 3 kolom ke-3 =  [6 9]

### Latihan-4 (Operasi matriks)

In [42]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]]) 

print(A , '\n')
print(B)

[[1 2]
 [7 8]] 

[[3 5]
 [1 6]]


Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B







In [43]:
#Ketik Kode disini

print('2xA = ', '\n', 2*A,'\n')

print('2+A = ', '\n', 2+A,'\n')

print('A+B = ', '\n', A+B,'\n')

print('A-B = ', '\n', A-B,'\n')

print('determinan matriks A = ', np.linalg.det(A),'\n')

D=np.linalg.inv(B)
print('D (Inverse B) =', '\n', D,'\n')

print('Transpose D = ', '\n', D.transpose(),'\n')

2xA =  
 [[ 2  4]
 [14 16]] 

2+A =  
 [[ 3  4]
 [ 9 10]] 

A+B =  
 [[ 4  7]
 [ 8 14]] 

A-B =  
 [[-2 -3]
 [ 6  2]] 

determinan matriks A =  -6.0 

D (Inverse B) = 
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]] 

Transpose D =  
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]] 



In [44]:
# Nilai eigen dan vektor eigen dari A dan B

print('nilai eigen matriks A = ', np.linalg.eig(A)[0])
print('vektor eigen matriks A = ','\n', np.linalg.eig(A)[1],'\n','\n')

print('nilai eigen matriks B = ', np.linalg.eig(B)[0])
print('vektor eigen matriks B = ','\n', np.linalg.eig(B)[1],'\n','\n')

nilai eigen matriks A =  [-0.62347538  9.62347538]
vektor eigen matriks A =  
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]] 
 

nilai eigen matriks B =  [1.8074176 7.1925824]
vektor eigen matriks B =  
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]] 
 



Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)? 

In [49]:
#Tunjukkan bedanya di kodingan di bawah ini
print('BxD Perkalian antar entry =','\n',B*D,'\n')
print('BxD Perkalian matriks =','\n',np.matmul(B,D),'\n')
print('Perbedaannya yaitu, pada pekalian antar entry perkalian dilakukan antar sesama elemen pada baris dan kolom yang sama. Sedangkan pada perkalian matriks metode yang digunakan yaitu barisxkolom')

BxD Perkalian antar entry = 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]] 

BxD Perkalian matriks = 
 [[ 1.00000000e+00 -5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00]] 

Perbedaannya yaitu, pada pekalian antar entry perkalian dilakukan antar sesama elemen pada baris dan kolom yang sama. Sedangkan pada perkalian matriks metode yang digunakan yaitu barisxkolom
